name: build linux kernel

on: [ push, pull_request ]

jobs:
  build-linux-kernel:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: build linux kernel image, then push docker image to docker hub
        shell: bash
        if: true
        run: |
          docker-compose -f docker-compose.yaml up --build kernel
          docker tag kernel ${{secrets.DOCKERHUBNAME}}/kernel:latest
          docker login -u ${{secrets.DOCKERHUBNAME}} -p ${{secrets.DOCKERHUBTOKEN}}
          docker push ${{secrets.DOCKERHUBNAME}}/kernel:latest

      - uses: actions/upload-artifact@v2
        with:
          name: kernel
          path: |
            ${{github.workspace}}/linux/arch/x86/boot/bzImage
            ${{github.workspace}}/linux/vmlinux*
            ${{github.workspace}}/linux/System.map
          if-no-files-found: error